// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFsimSDOGWOHBly9kBIIo45uHO569kFg',
    appId: '1:217092601021:web:2b7242faa156a3b01a33d4',
    messagingSenderId: '217092601021',
    projectId: 'gen-goals1',
    authDomain: 'gen-goals1.firebaseapp.com',
    storageBucket: 'gen-goals1.appspot.com',
    measurementId: 'G-2MH09Z9QC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJrTP6WKqGMSvlVRe6CaA8PTurgmmNqJg',
    appId: '1:217092601021:android:c2229f7cab06ec8b1a33d4',
    messagingSenderId: '217092601021',
    projectId: 'gen-goals1',
    storageBucket: 'gen-goals1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCToAF0S05xCIacOtpZ1PCte77OLxg4gLE',
    appId: '1:217092601021:ios:9bd3a2fc9d4272001a33d4',
    messagingSenderId: '217092601021',
    projectId: 'gen-goals1',
    storageBucket: 'gen-goals1.appspot.com',
    iosBundleId: 'com.example.flutterSamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCToAF0S05xCIacOtpZ1PCte77OLxg4gLE',
    appId: '1:217092601021:ios:9bd3a2fc9d4272001a33d4',
    messagingSenderId: '217092601021',
    projectId: 'gen-goals1',
    storageBucket: 'gen-goals1.appspot.com',
    iosBundleId: 'com.example.flutterSamples',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFsimSDOGWOHBly9kBIIo45uHO569kFg',
    appId: '1:217092601021:web:8b126f7fd35e91231a33d4',
    messagingSenderId: '217092601021',
    projectId: 'gen-goals1',
    authDomain: 'gen-goals1.firebaseapp.com',
    storageBucket: 'gen-goals1.appspot.com',
    measurementId: 'G-C0YG59BL4W',
  );
}
